controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_comment_add:
    path: /vehicle/{id}/comment
    controller: App\Controller\CommentController::addComment
